"""empty message

Revision ID: 648756f3e13c
Revises: 084eeeefc289
Create Date: 2025-12-03 11:57:42.458280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '648756f3e13c'
down_revision: Union[str, Sequence[str], None] = '084eeeefc289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('OPENAI', 'OPENAI_LIKE', 'JINA_AI', 'XAI', 'CUSTOM_OPENAI', 'TEXT_COMPLETION_OPENAI', 'COHERE', 'COHERE_CHAT', 'CLARIFAI', 'ANTHROPIC', 'ANTHROPIC_TEXT', 'BYTEZ', 'REPLICATE', 'RUNWAYML', 'HUGGINGFACE', 'TOGETHER_AI', 'OPENROUTER', 'DATAROBOT', 'VERTEX_AI', 'VERTEX_AI_BETA', 'GEMINI', 'AI21', 'BASETEN', 'AZURE', 'AZURE_TEXT', 'AZURE_AI', 'SAGEMAKER', 'SAGEMAKER_CHAT', 'BEDROCK', 'VLLM', 'NLP_CLOUD', 'PETALS', 'OOBABOOGA', 'OLLAMA', 'OLLAMA_CHAT', 'DEEPINFRA', 'PERPLEXITY', 'MISTRAL', 'MILVUS', 'GROQ', 'NVIDIA_NIM', 'CEREBRAS', 'AI21_CHAT', 'VOLCENGINE', 'CODESTRAL', 'TEXT_COMPLETION_CODESTRAL', 'DASHSCOPE', 'MOONSHOT', 'V0', 'MORPH', 'LAMBDA_AI', 'DEEPSEEK', 'SAMBANOVA', 'MARITALK', 'VOYAGE', 'CLOUDFLARE', 'XINFERENCE', 'FIREWORKS_AI', 'FRIENDLIAI', 'FEATHERLESS_AI', 'WATSONX', 'WATSONX_TEXT', 'TRITON', 'PREDIBASE', 'DATABRICKS', 'EMPOWER', 'GITHUB', 'COMPACTIFAI', 'CUSTOM', 'LITELLM_PROXY', 'HOSTED_VLLM', 'LLAMAFILE', 'LM_STUDIO', 'GALADRIEL', 'NEBIUS', 'INFINITY', 'DEEPGRAM', 'ELEVENLABS', 'NOVITA', 'AIOHTTP_OPENAI', 'LANGFUSE', 'HUMANLOOP', 'TOPAZ', 'ASSEMBLYAI', 'GITHUB_COPILOT', 'SNOWFLAKE', 'GRADIENT_AI', 'LLAMA', 'NSCALE', 'PG_VECTOR', 'HYPERBOLIC', 'RECRAFT', 'FAL_AI', 'HEROKU', 'AIML', 'COMETAPI', 'OCI', 'AUTO_ROUTER', 'VERCEL_AI_GATEWAY', 'DOTPROMPT', 'WANDB', 'OVHCLOUD', 'LEMONADE', name='llmproviders', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('title')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=sa.Enum('OPENAI', 'OPENAI_LIKE', 'JINA_AI', 'XAI', 'CUSTOM_OPENAI', 'TEXT_COMPLETION_OPENAI', 'COHERE', 'COHERE_CHAT', 'CLARIFAI', 'ANTHROPIC', 'ANTHROPIC_TEXT', 'BYTEZ', 'REPLICATE', 'RUNWAYML', 'HUGGINGFACE', 'TOGETHER_AI', 'OPENROUTER', 'DATAROBOT', 'VERTEX_AI', 'VERTEX_AI_BETA', 'GEMINI', 'AI21', 'BASETEN', 'AZURE', 'AZURE_TEXT', 'AZURE_AI', 'SAGEMAKER', 'SAGEMAKER_CHAT', 'BEDROCK', 'VLLM', 'NLP_CLOUD', 'PETALS', 'OOBABOOGA', 'OLLAMA', 'OLLAMA_CHAT', 'DEEPINFRA', 'PERPLEXITY', 'MISTRAL', 'MILVUS', 'GROQ', 'NVIDIA_NIM', 'CEREBRAS', 'AI21_CHAT', 'VOLCENGINE', 'CODESTRAL', 'TEXT_COMPLETION_CODESTRAL', 'DASHSCOPE', 'MOONSHOT', 'V0', 'MORPH', 'LAMBDA_AI', 'DEEPSEEK', 'SAMBANOVA', 'MARITALK', 'VOYAGE', 'CLOUDFLARE', 'XINFERENCE', 'FIREWORKS_AI', 'FRIENDLIAI', 'FEATHERLESS_AI', 'WATSONX', 'WATSONX_TEXT', 'TRITON', 'PREDIBASE', 'DATABRICKS', 'EMPOWER', 'GITHUB', 'COMPACTIFAI', 'CUSTOM', 'LITELLM_PROXY', 'HOSTED_VLLM', 'LLAMAFILE', 'LM_STUDIO', 'GALADRIEL', 'NEBIUS', 'INFINITY', 'DEEPGRAM', 'ELEVENLABS', 'NOVITA', 'AIOHTTP_OPENAI', 'LANGFUSE', 'HUMANLOOP', 'TOPAZ', 'ASSEMBLYAI', 'GITHUB_COPILOT', 'SNOWFLAKE', 'GRADIENT_AI', 'LLAMA', 'NSCALE', 'PG_VECTOR', 'HYPERBOLIC', 'RECRAFT', 'FAL_AI', 'HEROKU', 'AIML', 'COMETAPI', 'OCI', 'AUTO_ROUTER', 'VERCEL_AI_GATEWAY', 'DOTPROMPT', 'WANDB', 'OVHCLOUD', 'LEMONADE', name='llmproviders', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
