"""empty message

Revision ID: 70b97a818dc4
Revises: 
Create Date: 2025-11-13 11:32:24.786636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from db.models.provider import LlmModelCapability
from db.models.task import TaskMessage
from db.models.utils import DataClassJSON
from db.models.utils import DataclassListJSON

# revision identifiers, used by Alembic.
revision: str = '70b97a818dc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OPENAI', 'ANTHROPIC', 'GEMINI', name='providertype', native_enum=False), nullable=False),
    sa.Column('base_url', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('directory', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('context_size', sa.Integer(), nullable=False),
    sa.Column('capability', DataClassJSON(LlmModelCapability), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('model', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['model'], ['llm_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Agent', 'Orchestration', name='tasktype', native_enum=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('messages', DataclassListJSON(TaskMessage), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workspace_agent_association',
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('workspace_id', 'agent_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workspace_agent_association')
    op.drop_table('tasks')
    op.drop_table('agents')
    op.drop_table('llm_models')
    op.drop_table('workspaces')
    op.drop_table('providers')
    # ### end Alembic commands ###
