"""empty message

Revision ID: 9a197b6f33e7
Revises: 798622f8bdad
Create Date: 2026-01-02 16:22:43.741563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a197b6f33e7'
down_revision: Union[str, Sequence[str], None] = '798622f8bdad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_name', sa.String(), nullable=False))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_run_at', sa.Integer(), nullable=False))

    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_background', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_column('workspace_background')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('last_run_at')

    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_column('icon_name')

    # ### end Alembic commands ###
